version: "3.4"

services:
  ib-gateway:
    restart: always
    container_name: tbot-on-tradingboat
    build:
      context: ./stable
      args:
        TBOT_TRADINGBOAT_GIT_REPO: ${TBOT_TRADINGBOAT_GIT_REPO:-https://github.com/PlusGenie/tbot-tradingboat.git}
    environment:
      TVWB_UNIQUE_KEY: ${TVWB_UNIQUE_KEY:-}
      TVWB_HTTPS_PORT: ${TVWB_HTTPS_PORT:-5000}
      TBOT_LOGLEVEL: ${TBOT_LOGLEVEL:-DEBUG}
      TBOT_IB_LOGLEVEL: ${TBOT_IB_LOGLEVEL:-DEBUG}
      TBOT_PRODUCTION: ${TBOT_PRODUCTION:-False}
      TBOT_REDIS_HOST: ${TBOT_REDIS_HOST:-redis}
      TBOT_REDIS_PORT: ${TBOT_REDIS_PORT:-6379}
      TBOT_REDIS_PASSWORD: ${TBOT_REDIS_PASSWORD:-}
      TBOT_USES_REDIS_STREAM: ${TBOT_USES_REDIS_STREAM:-False}
      TBOT_REDIS_READ_TIMEOUT_MS: ${TBOT_REDIS_READ_TIMEOUT_MS:-10}
      TBOT_IBKR_PORT: ${TBOT_IBKR_PORT:-4001}
      TBOT_IBKR_CLIENTID: ${TBOT_IBKR_CLIENTID:-1}
      TBOT_IBKR_IPADDR: ${TBOT_IBKR_IPADDR:-127.0.0.1}
      TBOT_DB_HOME: ${TBOT_DB_HOME:-}
      TBOT_DB_OFFICE: ${TBOT_DB_OFFICE:-}
      TBOT_DISCORD_WEBHOOK: ${TBOT_DISCORD_WEBHOOK:-}
      TBOT_TELEGRAM_TOKEN: ${TBOT_TELEGRAM_TOKEN:-}
      TBOT_TELEGRAM_CHAT_ID: ${TBOT_TELEGRAM_CHAT_ID:-}
      TBOT_NGROK: ${TBOT_NGROK:-}
      TBOT_PROFILER: ${TBOT_PROFILER:-False}
    ports:
      - "0.0.0.0:5000:5000"
    depends_on:
      - redis
      - ngrok

  redis:
    image: redis:7.0.10-alpine
    restart: always
    container_name: redis-on-tradingboat

  ngrok:
    image: ngrok/ngrok:3.5.0-alpine
    restart: always
    container_name: ngrok-on-tradingboat
    command:
      - http
      - "${NGROK_PORT}"
    ports:
      - "4040:4040"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTH}
      NGROK_REGION: us
      NGROK_PORT: ${NGROK_PORT:-}
